### ISSUE TITLE
ergonomy to improve 

### ISSUE THREAD

**Issue by rdc5163** [thasmin/Podax#220]
Hello, 
In the current version I use (3.5), the icons needed to play the files (play, forward, backward, stop, etc.) are very close to the button 'remove from queue'. 
So it is easy to remove the podcast by error, just by trying to play forward or backward the audio. The button 'remove from queue' should rather be at the bottom of the screen.

**Comment by thasmin** [comment]
Version 3.5 is very old, although it looks like the latest on F-droid. I think version 6 was the last that was published on the Play Store and I believe it addresses this issue. I've stopped publishing updates because I don't have the time, unfortunately. Check out Pocket Casts or AntennaPod if you want something open source.
